TOTAL_NUM_OF_VALIDATORS = 10

ALL_VALIDATORS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

QUORUM_SETS = [[4, ALL_VALIDATORS], [4, ALL_VALIDATORS], [4, ALL_VALIDATORS], [4, ALL_VALIDATORS], [4, ALL_VALIDATORS], [4, ALL_VALIDATORS], [4, ALL_VALIDATORS], [4, ALL_VALIDATORS], [4, ALL_VALIDATORS], [4, ALL_VALIDATORS]]

