TOTAL_NUM_OF_VALIDATORS = 11

ALL_VALIDATORS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

QUORUM_SETS = [[5, ALL_VALIDATORS], [5, ALL_VALIDATORS], [5, ALL_VALIDATORS], [5, ALL_VALIDATORS], [5, ALL_VALIDATORS], [5, ALL_VALIDATORS], [5, ALL_VALIDATORS], [5, ALL_VALIDATORS], [5, ALL_VALIDATORS], [5, ALL_VALIDATORS], [5, ALL_VALIDATORS]]

TRY_FIND_CAND_LIMIT = 10
